//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenAbelardoCastro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Display(Name = "#")]
        public int clienteId { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Display(Name = "Rut")]
        public string rut { get; set; }

        [Display(Name = "Razón Social")]
        public string razonSocial { get; set; }

        [Display(Name = "Dirección")]
        public Nullable<int> ciudadId { get; set; }

        [Display(Name = "Categoria")]
        public Nullable<int> categoriaId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Ciudad Ciudad { get; set; }
    }
}
